### ISSUE TITLE
0.1.6 does not work in Java 11

### ISSUE THREAD

**Issue by gmatadh** [airbrake/log4javabrake2#19]
`2021-12-17 23:13:42,774 main WARN Could not examine class io/airbrake/log4javabrake2/AirbrakeAppender.class java.lang.UnsupportedClassVersionError: io/airbrake/log4javabrake2/AirbrakeAppender has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	`

`  Last modified Dec 16, 2021; size 7427 bytes
  MD5 checksum a12d7519ac1bc8b95d721b7920ed6221
  Compiled from "AirbrakeAppender.java"
public class io.airbrake.log4javabrake2.AirbrakeAppender extends org.apache.logging.log4j.core.appender.AbstractAppender
  minor version: 0
  major version: 58
`

**Comment by rpvilao** [comment]
I don't see the error (the javabrake one) but I am not getting them pushed to my airbrake account. Something seems wrong (I believe it's also happening with 0.1.5).

**Comment by mmcdaris** [comment]
Thank you for reporting this issue! Please download log4Javabrake2 version `0.1.7` to pick up the fix. 

We apologize for the problems with this version. Our last release was built and released with the wrong JDK version, it needs to be java version `11`. We've corrected the issue, improved our release guides, and verified the `AirbrakeAppender` now reports a class file version of `55` once again(`javap -verbose <CLASSFILE> | grep "major"`). If either of you have any further issues we're happy to help!

**Comment by rpvilao** [comment]
I tried with 0.1.7 and it's still not working for me. Here's my classpath for airbrake related libs:

```
root@9b76848f1cd6:/usr/local/tomcat/webapps/ROOT# find . -name "*brake*"
./WEB-INF/lib/javabrake-0.2.3.jar
./WEB-INF/lib/log4javabrake2-0.1.7.jar
```

**Comment by rpvilao** [comment]
@mmcdaris any news regarding this issue? Any other reasons why I am not getting traces?

**Comment by mmcdaris** [comment]
Thanks for the info @rpvilao, I'm looking into this issue once more.

**Comment by mmcdaris** [comment]
Sorry for the delay @rpvilao Please try once more with version v0.1.8 of log4javabrake and either the default version of  javabrake or v0.2.4. I've included a few more security patches in the most recent version as well so all the more reason to upgrade. Let me know how it goes for you🤞. I've just released the new version so please make sure it shows [up here](https://repo1.maven.org/maven2/io/airbrake/log4javabrake2/) before you try version 0.1.8.

**Comment by rpvilao** [comment]
@mmcdaris thanks for the update. Unfortunately, it's not working yet. Since no one else is complaining, I believe this might be a problem with my classpath world:

>root@c2f3bdbef36f:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib# find . -name "*brake*"
./log4javabrake2-0.1.8.jar
./javabrake-0.2.4.jar
root@c2f3bdbef36f:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib# find . -name "*log4*"
./log4j-slf4j-impl-2.17.0.jar
./spring-boot-starter-log4j2-2.4.2.jar
./log4javabrake2-0.1.8.jar
./log4j-core-2.17.0.jar
./log4j-jul-2.17.0.jar
./log4j-api-2.17.0.jar


I guess something is implicating it. Could it be for example this spring boot starter log? I am eager to explore more, but I would like to know how to approach this debugging.

**Comment by rpvilao** [comment]
Ok got it... I was missing the package declaration in the configuration tag. For some reason, this was working before in previous versions of log4j. Sorry about it, you can close the issue.
